name: 'test'

inputs:
  project-dir:
    description: 'Project folder to inspect (default ${{env.GITHUB_WORKSPACE}})'
    required: false
    default: '/github/workspace'
  results-dir:
    description: 'Save results to folder (default ${{env.GITHUB_WORKSPACE}}/qodana)'
    required: false
    default: '/github/workspace/qodana'
  report-dir:
    description: 'Save html report to folder (default ${{env.GITHUB_WORKSPACE}}/qodana-report)'
    required: false
    default: '/github/workspace/qodana-report'
  cache-dir:
    description: 'Save cache to folder (default ${{env.HOME}}/qodana-cache)'
    required: false
    default: '/github/home/qodana-cache'
runs:
  using: 'docker'
  image: 'docker://jetbrains/qodana:latest'
  args:
    - --project-dir=${{inputs.project-dir}}
    - --results-dir=${{inputs.results-dir}}
    - --report-dir=${{inputs.report-dir}}
    - --cache-dir=${{inputs.cache-dir}}
    - --save-report
