name: 'test'

inputs:
  project-dir:
    description: 'Project folder to inspect  (default: whole project)'
    required: false
    default: '${{github.workspace}}'
  results-dir:
    description: 'Save results to folder (default: qodana)'
    required: false
    default: "${{ github.workspace }}/qodana"
  cache-dir:
    description: 'Save cache to folder'
    required: false
    default: "/home/runner/work/_temp/_github_home/qodana-cache"
runs:
  using: 'composite'
  steps:
    # create dirs as user, or docker would create as root
    - shell: bash
      run: mkdir -p "${{inputs.results-dir}}" "${{inputs.cache-dir}}"
    - shell: bash
      run: docker run -u $(id -u) -v ${{inputs.project-dir}}:/data/project -v ${{inputs.results-dir}}/qodana:/data/results -v ${{inputs.cache-dir}}:/data/cache jetbrains/qodana:2021.1-eap --save-report
    - shell: bash
      run: |
        ls -la ${{inputs.project-dir}}
        ls -la ${{inputs.project-dir}}/logs
        ls -la ${{inputs.results-dir}}
        ls -la ${{inputs.cache-dir}}
        cat ${{inputs.project-dir}}/logs/*
        
