name: 'Test - code inspection'

runs:
  using: "composite"
  steps:
    - run: docker run -v ${GITHUB_WORKSPACE}:/data/project -v ${GITHUB_WORKSPACE}/qodana:/data/results jetbrains/qodana:2020.3-eap --save-report
      shell: sh
  
#     - run:  
#     name: Archive results
#       uses: actions/upload-artifact@v2
#       with:
#         name: qodana-results
#         if-no-files-found: error
#         path: qodana/report/results
         
#     - name: Print results
#       run: |
#         echo "Qodana - Code Inspection has finished successfully!"
#         echo "Download an artifact qodana-results.zip. Code Inspection results are part of file result-allProblems.json."
#         echo "________________________________________________________________"
#         cat ${GITHUB_WORKSPACE}/qodana/report/results/result-allProblems.json
         
#     - name: Archive error logs
#       uses: actions/upload-artifact@v2
#       if: failure()
#       with:
#         name: qodana-error-logs
#         path: qodana
        
#     - name: Print error message
#       if: failure()
#       run: |
#         echo "Qodana - Code Inspection has failed"
#         echo "Please contact our support team by email at qodana-support@jetbrains.com. Attach qodana-error-logs.zip to your message."
