name: 'test'

inputs:
  project-dir:
    description: 'Project folder to inspect'
    required: false
    default: "${{ github.workspace }}"
  results-dir:
    description: 'Save results to folder'
    required: false
    default: "${{ github.workspace }}/qodana"
  cache-dir:
    description: 'Save cache to folder'
    required: false
    default: "/home/runner/work/qodana-cache"
runs:
  using: 'composite'
  steps:
    - run: mkdir -p ${{inputs.cache-dir}} ${{inputs.results-dir}} # ${{inputs.results-dir}}/log
      shell: bash
    - run: sudo chown -R $(id -g) ${{inputs.cache-dir}} ${{inputs.results-dir}}
      shell: bash
    - run: echo "workspace=${{ github.workspace }}" ; ls -la ${{ github.workspace }}/ ; echo "qodana-cache" ; ls -la  ${{inputs.cache-dir}} ; echo "qodana" ; ls -laR ${{inputs.results-dir}}
      shell: bash
    - run: docker run -u $(id -u):$(id -g) -v ${{inputs.project-dir}}:/data/project -v ${{inputs.results-dir}}/qodana:/data/results -v  ${{inputs.cache-dir}}:/data/cache/ jetbrains/qodana:latest "--save-report"
      shell: bash
