name: 'test'

inputs:
  project-dir:
    description: 'Project folder to inspect'
    required: false
    default: "$GITHUB_WORKSPACE"
  results-dir:
    description: 'Save results to folder'
    required: false
    default: "$GITHUB_WORKSPACE/qodana"
  report-dir:
    description: 'Save html report to folder'
    required: false
    default: "$GITHUB_WORKSPACE/qodana-report"
  cache-dir:
    description: 'Save cache to folder'
    required: false
    default: "$HOME/qodana-cache"
runs:
  using: 'composite'
  steps: 
    - run: docker run  -v ${{inputs.project-dir}}:/data/project -v ${{inputs.results-dir}}/data/results -v ${{inputs.cache-dir}}:/data/cache/ jetbrains/qodana:latest "--save-report" #-u $(id -u):$(id -g)
      shell: bash
