name: Test home

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  code_inspection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create dirs
        run: |
          mkdir -p  /home/runner/work/qodana-cache ${{ github.workspace }}/qodana
          ls -lh ${{ github.workspace }}/
          ls -lh  /home/runner/work/qodana-cache/
        
  
      - name: Cache Qodana dependencies
        uses: actions/cache@v2
        with:
          path: /home/runner/work/qodana-cache
          key: ${{ runner.os }}-qodana-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-${{ github.ref }}
            ${{ runner.os }}-qodana-
            
      - name: Echo
        run: |
          echo "workspace"
          ls -lh ${{ github.workspace }}/
          echo "qodana-cache"
          ls -lh  /home/runner/work/qodana-cache/
          
      - name: Run Qodana
        run: docker run -u $(id -u) -v ${{ github.workspace }}:/data/project -v ${{ github.workspace }}/qodana:/data/results -v  /home/runner/work/qodana-cache:/data/cache/ jetbrains/qodana:latest "--save-report"
        
      - run: |
          ls -lh ${{ github.workspace }}/qodana/
          ls -lR  /home/runner/work/qodana-cache/
      
          
