name: Qodana - Code Inspection

on:
  workflow_dispatch:

jobs:
  code_inspection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Qodana dependencies
        uses: actions/cache@v2
        with:
          path: ~/work/_temp/_github_home/cache
          key: ${{ runner.os }}-qodana-test2HomeDir-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-test2HomeDir-${{ github.ref }}
            ${{ runner.os }}-qodana-test2HomeDir-

      - name: Qodana - Code Inspection
        uses:  a-kuznetsova/java-examples@2021.6
        with:
          cache-dir: /github/home/cache

      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: qodana-results
          if-no-files-found: error
          path: qodana-report/results
          
      - name: Print results
        run: |
          ls -lh ~/work/_temp/_github_home/
          ls -lh ~/work/_temp/_github_home/cache/
