
name: Qodana - Code Inspection

on:
  workflow_dispatch:

jobs:
  code_inspection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run Code Inspection
        run: docker run -v  ${GITHUB_WORKSPACE}:/data/project -v ${GITHUB_WORKSPACE}/qodana:/data/results jetbrains/qodana:2020.3-eap --save-report
        
      - name: Bash
        run: |
         echo $GITHUB_WORKSPACE
         echo --------------------------------
         ls $GITHUB_WORKSPACE/
         echo --------------------------------
         ls $GITHUB_WORKSPACE/qodana/
         echo --------------------------------
         ls ${GITHUB_WORKSPACE}/qodana/report/results
        
      - name: Archive qodana results
        uses: actions/upload-artifact@v2
        with:
          name: qodana-results
          path: |
            ${GITHUB_WORKSPACE}/qodana/report/results
