name: Qodana - Code Inspection

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  code_inspection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Qodana dependencies
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/qodana-cache
          key: ${{ runner.os }}-qodana-cache-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-cache-${{ github.ref }}
            ${{ runner.os }}-qodana-cache-


      - name: Qodana - Code Inspection
        uses:  a-kuznetsova/java-examples@2021.7
        with:
          cache-dir:  ${{ github.workspace }}/qodana-cache
      
                  
      - run:  |
          echo  ${{ github.workspace }}
          if [ -d "${{ github.workspace }}/qodana-cache" ]; then
            ls -lh  ${{ github.workspace }}/qodana-cache
            chown -R $(id -u) ${{ github.workspace }}/qodana-cache
          fi
          
      - name: Archive error logs
        uses: actions/upload-artifact@v2
        with:
          name: qodana-logs
          path: ${{ env.GITHUB_WORKSPACE }}/qodana-cache
