name: Test home

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  code_inspection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Cache Qodana dependencies
        uses: actions/cache@v2
        with:
          path: /home/runner/work/qodana-cache
          key: ${{ runner.os }}-qodana-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-${{ github.ref }}
            ${{ runner.os }}-qodana-
            
      - name: Echo
        run: |
          echo "uid=$(id --user)"
          echo "workspace=${{ github.workspace }}"
          ls -la ${{ github.workspace }}/
          echo "qodana-cache"
          ls -la  /home/runner/work/qodana-cache/

      - name: Run Qodana
        uses: a-kuznetsova/java-examples@2021.19
        
      - run: |
          ls -lh ${{ github.workspace }}/qodana/
          ls -lR  /home/runner/work/qodana-cache/
      
          
