name: Test home

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  code_inspection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache Qodana dependencies
        uses: actions/cache@v2
        with:
          path: /home/runner/work/qodana-cache
          key: ${{ runner.os }}-qodana-cache-0b75d027b97e564599565451daef66a8992065b5
          restore-keys: |
            ${{ runner.os }}-qodana-cache-0b75d027b97e564599565451daef66a8992065b5
      
      - name: Run Qodana
        uses: a-kuznetsova/java-examples@0b75d027b97e564599565451daef66a8992065b5

      
          
