name: Test home

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  code_inspection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache Qodana dependencies
        uses: actions/cache@v2
        with:
          path: /home/runner/work/qodana-cache
          key: ${{ runner.os }}-qodana-cache-5874410cf209c5d42654e082b50abb939ccf87bd
          restore-keys: |
            ${{ runner.os }}-qodana-cache-5874410cf209c5d42654e082b50abb939ccf87bd
      
      - name: Run Qodana
        uses: a-kuznetsova/java-examples@5874410cf209c5d42654e082b50abb939ccf87bd

      
          
