name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /home/runner/work/qodana-cache
          key: ${{ runner.os }}-qodana-test5633034_test-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-test5633034_test-${{ github.ref }}
            ${{ runner.os }}-qodana-test5633034_test-
            
      - uses: a-kuznetsova/java-examples@main
        with:
          results-dir: /home/runner/work/java-examples/java-examples/results/qodana
          cache-dir: /home/runner/work/qodana-cache
          
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/qodana
