name: Qodana - Code Inspection

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  code_inspection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Qodana dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.GITHUB_WORKSPACE }}/qodana-cache
          key: ${{ runner.os }}-qodana-cache-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-cache-${{ github.ref }}
            ${{ runner.os }}-qodana-cache-
            
      - run:  |
          echo ${{ env.GITHUB_WORKSPACE }}
          if [ -d "${{ env.GITHUB_WORKSPACE }}/qodana-cache" ]; then
            ls -lh ${{ env.GITHUB_WORKSPACE }}/qodana-cache
          fi

      - name: Qodana - Code Inspection
        uses:  a-kuznetsova/java-examples@2021.7
        with:
          cache-dir: ${{ env.GITHUB_WORKSPACE }}/qodana-cache
        
      - name: Archive error logs
        uses: actions/upload-artifact@v2
        with:
          name: qodana-logs
          path: ${{ env.GITHUB_WORKSPACE }}/qodana-cache
