name: Test home

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  code_inspection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache Qodana dependencies
        uses: actions/cache@v2
        with:
          path: /home/runner/work/qodana-cache
          key: ${{ runner.os }}-qodana-cache-test4564-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-cache-test4564-${{ github.ref }}
            ${{ runner.os }}-qodana-cache-test4564-
      
      - name: Run Qodana
        uses: a-kuznetsova/java-examples@composite_2021.1
            
      - name: Change permission
        run: sudo chmod -R a+rwx,u-w,g-w,o-w /home/runner/work/qodana-cache

      
          
