name: Qodana - Code Inspection

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  code_inspection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Qodana dependencies
        uses: actions/cache@v2
        with:
          path: $HOME/cache
          key: ${{ runner.os }}-qodana-test2HomeDir3-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-test2HomeDir3-${{ github.ref }}
            ${{ runner.os }}-qodana-test2HomeDir3-

      - name: Qodana - Code Inspection
        uses:  a-kuznetsova/java-examples@2021.7
        
      - name: Archive error logs
        uses: actions/upload-artifact@v2
        with:
          name: qodana-logs
          path: $HOME/cache
