name: Test home

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  code_inspection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Cache Qodana dependencies
        uses: actions/cache@v2
        with:
          path: /home/runner/work/qodana-cache
          key: ${{ runner.os }}-qodana-cache3-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-cache3-${{ github.ref }}
            ${{ runner.os }}-qodana-cache3-

      - name: Run Qodana
        uses: a-kuznetsova/java-examples@2021.26
        with:
            results-dir: "/home/runner/work/qodana-results"
            
      - name: Echo
        run: sudo chmod -R 555 /home/runner/work/qodana-cache

      
          
