name: Test
on:
  workflow_dispatch:

jobs:
  code_inspection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create file
      - run: touch ${GITHUB_WORKSPACE}/qodana/qodana-results.json

      - name: upload file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"
      
      - uses: docker://amazon/aws-cli
      - run: aws s3 sync ${GITHUB_WORKSPACE}/qodana/ qodana-github/results/result1/results/
      
